site_name: Meteor-Z 个人博客
site_description: 个人博客
site_author: 刘泽辰
copyright: Metoer-Z
repo_url: https://github.com/Meteor-Z/Meteor-Z.github.io
site_url: http://liuzechen.top
nav: 
  - 文章:
    - software_list.md
    - network_problem.md
    - lecture.md
    - assembly_language.md
    - classicpictures.md
    - 计算机网络: network.md 
  - 其他:
    - interview.md 
    - client_bible.md
    - web_build.md
    - 实习有感: practice_feel.md
  - 八股:
    - mysql: mysql.md
    - redis: redis.md
  - 工具:
    - git: git.md
  - 资料: summarize.md
  - GitHub: https://github.com/Meteor-Z
  - 知乎: https://www.zhihu.com/people/newlzc 
plugins:
  - search
theme: 
  name: material
  language: zh
  features:
    - content.code.copy # 代码复制
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences: