site_name: Meteor-Z 个人博客
site_description: 个人博客
site_author: 刘泽辰
copyright: Metoer-Z
repo_url: https://github.com/Meteor-Z/Meteor-Z.github.io
site_url: http://liuzechen.top
nav:
  - 文章:
    - summarize.md
    - software_list.md
    - network_problem.md
    - lecture.md
  - 其他:
    - interview.md 
    - client_bible.md
  - GitHub: https://github.com/Meteor-Z
  - 知乎: https://www.zhihu.com/people/newlzc 
plugins:
  - search
  - macros
  - print-site
theme: 
  name: mkdocs
  palette:
    primary: blue grey
  font:
    code: Noto Sans Simplified Chinese
  features:
    - search.suggest
    - search.highlight
  highlightjs: true
  hljs_languages: # rg '^```\w+' | sed 's/.*:```\(\w*\)/    - \1/g' | sort | uniq
    - bash
    - c
    - cmake
    - cpp
    - diff
    - java
    - json
    - llvm
    - nasm
    - python
    - rust
    - txt
    - powershell
extra_javascript:
  - extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css: 
  - extra.css
markdown_extensions:
  - sane_lists
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - pymdownx.arithmatex
  - mdx_truly_sane_lists # 支持嵌套列表的